# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'GitHub Release CI'
description: 'Release CI used for GitHub releases'
inputs:
  github-token:
    description: 'A GitHub token (required to upload to the release)'
    required: true
  upload-url:
    description: 'The release upload URL for the asset'
    required: true
runs:
  using: "composite"
  steps:
  - name: Translate Repo Name For Build Tools filename_prefix
    id: repo-name
    shell: bash
    run: |
      echo repo-name=$(
      echo ${{ github.repository }} |
      awk -F '\/' '{ print tolower($2) }' |
      tr '_' '-'
      ) >> $GITHUB_OUTPUT
  - name: Set up Python 3.x
    uses: actions/setup-python@v4
    with:
      python-version: "3.x"
  - name: Versions
    shell: bash
    run: |
      python3 --version
  - name: Checkout Current Repo
    uses: actions/checkout@v2
    with:
      submodules: true
  - name: Checkout tools repo
    uses: actions/checkout@v2
    with:
      repository: adafruit/actions-ci-circuitpython-libs
      path: actions-ci
  - name: Install deps
    shell: bash
    run: |
      source actions-ci/install.sh
  - name: Build assets
    shell: bash
    run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location .
  - name: Upload Release Assets
    uses: shogo82148/actions-upload-release-asset@v1
    with:
      asset_path: "bundles/*"
      github_token: ${{ inputs.github-token }}
      upload_url: ${{ inputs.upload-url }}
