# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'GitHub Release CI'
description: 'Release CI used for GitHub releases'
inputs:
  github-token:
    description: 'A GitHub token (required to upload to the release)'
    required: true
  upload-url:
    description: 'The release upload URL for the asset'
    required: true
  python-version:
    description: 'The version of Python to use in the CI'
    required: true
    default: '3.11'
  package-prefix:
    description: |
      The prefix (or name) of your package (if applicable) to use
      for GitHub releases
    required: true
    default: ""
  ignore-bundles:
    description: |
      A comma and space separated list of bundles to be skipped when building.
      Valid options are py, mpy, example, and json.  For example, to skip
      building the MPY and example bundles, this field would be: mpy, example
    required: true
    default: ""
runs:
  using: "composite"
  steps:
  - name: Translate Repo Name For Build Tools filename_prefix
    id: repo-name
    shell: bash
    run: |
      echo repo-name=$(
      echo ${{ github.repository }} |
      awk -F '\/' '{ print tolower($2) }' |
      tr '_' '-'
      ) >> $GITHUB_OUTPUT
  - name: Set up requested Python version
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
  - name: Versions
    shell: bash
    run: |
      python3 --version
  - name: Checkout Current Repo
    uses: actions/checkout@v4
    with:
      submodules: true
      show-progress: false
  - name: Checkout tools repo
    uses: actions/checkout@v4
    with:
      show-progress: false
      repository: adafruit/actions-ci-circuitpython-libs
      path: actions-ci
  - name: Install deps
    shell: bash
    run: |
      source actions-ci/install.sh
  - name: Add the given package filename_prefix
    id: package-prefix-arg
    shell: bash
    run: |
      if [ "${{ inputs.package-prefix }}" == "" ]; then
        echo prefix-arg="" >> $GITHUB_OUTPUT
      else
        echo prefix-arg="--package_folder_prefix ${{ inputs.package-prefix }}" >> $GITHUB_OUTPUT
      fi
  - name: Add the given bundle ignores
    id: ignore-bundles-arg
    shell: bash
    run: |
      if [ "${{ inputs.ignore-bundles }}" == "" ]; then
        echo ignore-bundles="" >> $GITHUB_OUTPUT
      else
        echo ignore-bundles='--ignore "${{ inputs.ignore-bundles }}"' >> $GITHUB_OUTPUT
      fi
  - name: Build assets
    shell: bash
    run: |
      circuitpython-build-bundles \
      --filename_prefix ${{ steps.repo-name.outputs.repo-name }} \
      --library_location . \
      ${{ steps.package-prefix-arg.outputs.prefix-arg }} \
      ${{ steps.ignore-bundles-arg.outputs.prefix-arg }}
  - name: Upload Release Assets
    uses: shogo82148/actions-upload-release-asset@v1
    with:
      asset_path: "bundles/*"
      github_token: ${{ inputs.github-token }}
      upload_url: ${{ inputs.upload-url }}
