# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'GitHub Release CI'
description: 'Release CI used for GitHub releases'
inputs:
  github-token:
    description: 'A GitHub token (required to upload to the release)'
    required: true
  upload-url:
    description: 'The release upload URL for the asset'
    required: true
  python-version:
    description: 'The version of Python to use in the CI'
    required: true
    default: '3.x'
  package-prefix:
    description: |
      The prefix (or name) of your pacakge (if applicable) to use
      for GitHub releases
    required: true
    default: ""
runs:
  using: "composite"
  steps:
  - name: Translate Repo Name For Build Tools filename_prefix
    id: repo-name
    shell: bash
    run: |
      echo repo-name=$(
      echo ${{ github.repository }} |
      awk -F '\/' '{ print tolower($2) }' |
      tr '_' '-'
      ) >> $GITHUB_OUTPUT
  - name: Set up Python 3.x
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - name: Versions
    shell: bash
    run: |
      python3 --version
  - name: Checkout Current Repo
    uses: actions/checkout@v3
    with:
      submodules: true
  - name: Checkout tools repo
    uses: actions/checkout@v3
    with:
      repository: adafruit/actions-ci-circuitpython-libs
      path: actions-ci
  - name: Install deps
    shell: bash
    run: |
      source actions-ci/install.sh
  - name: Add the given package filename_prefix
    id: package-prefix-arg
    shell: bash
    run: |
      if [ "${{ inputs.package-prefix }}" == "" ]; then
        echo prefix-arg="" >> $GITHUB_OUTPUT
      else
        echo prefix-arg="--package_folder_prefix ${{ inputs.package-prefix }}" >> $GITHUB_OUTPUT
      fi
  - name: Build assets
    shell: bash
    run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location . ${{ steps.package-prefix-arg.outputs.prefix-arg }}
  - name: Upload Release Assets
    uses: shogo82148/actions-upload-release-asset@v1
    with:
      asset_path: "bundles/*"
      github_token: ${{ inputs.github-token }}
      upload_url: ${{ inputs.upload-url }}
