# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'GitHub Release CI'
description: 'Release CI used for PyPI releases'
inputs:
  pypi-username:
    description: 'The PyPI username for twine'
    required: true
  pypi-password:
    description: 'The PyPI password for twine'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v1
  - name: Check For pyproject.toml
    id: need-pypi
    shell: bash
    run: |
      echo pyproject-toml=$( find . -wholename './pyproject.toml' ) >> $GITHUB_OUTPUT
  - name: Set up Python
    if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
  - name: Install dependencies
    if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install --upgrade build twine
  - name: Build and publish
    if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
    env:
      TWINE_USERNAME: ${{ inputs.pypi-username }}
      TWINE_PASSWORD: ${{ inputs.pypi-password }}
    shell: bash
    run: |
      find -type f -not -path "./.*" -not -path "./docs*" \( -name "*.py" -o -name "*.toml" \) -exec sed -i -e "s/0.0.0+auto.0/${{github.event.release.tag_name}}/" {} +
      python -m build
      twine upload dist/*
